### ISSUE TITLE
Spec refining: Relative paths in IPLD

### ISSUE THREAD

**Issue by nicola** [ipld/specs#1]
(reposted from https://github.com/ipfs/specs/issues/112)

Originally in [interplanetary paths](https://github.com/nicola/cross-data-paths) I included the possibility of having relative paths.

Here I am proposing to add in the specs (and in the js-ipld implementation), the ability to resolve relative paths.
Having relative paths saves space (`../`, instead of a full hash), helps avoiding splitting things in multiple pieces (`../` instead of creating a new object) and finally, allow circular relationships: **merkle graph**!

```
{
  nicola: { '/': hashNicola },
  david: { '/': hashDavid }
}

{
  name: "Nicola",
  friends: [{'/':'../david' }]
}

{
  name: "David",
  friends: [{'/':'../nicola' }]
}
```

---

cc @jbenet, @mildred, @dignifiedquire

**Comment by dignifiedquire** [comment]
Would these relative paths be restricted to the current object?

**Comment by nicola** [comment]
We could either restrict them to the current object or as in the proposed in the example, for external objects

**Comment by jbenet** [comment]
- On one hand, i think this violates the idea of the DAG and will be confusing to people. It's _ultimately a dag_, but one typical property of DAGs is that when you traverse down an edge, you won't find parts you've already traversed. This effectively turns the DAG into a DG with the possibility of traversal cycles. I don't like that.
- We need to flesh out a lot more complex examples and find "where it confuses everything". Meaning let's figure out "how confusing can this get" and see if we want to stomach that confusion/complexity.
- I think if we do this, we should not restrict it to current objects. it breaks the "transparent resolution" abstraction.

**Comment by jbenet** [comment]
here's some fun

``` yml
---
# obj1
a: ../

# what does /ipld/<obj1-cid>/a/a/a/a/a/a/a/a/a/a point to?
```

---

``` yml
---
# obj2
a:
  aa:
    aaa: ../../../a/aa/aaa
aa:
  a: ../../
  aa: ../../
  aaa: ../../

---
#  obj3
a: <obj2-cid>/aa
aa: <obj2-cid>/a/aa
aaa: <obj2-cid>/a/aa

# what does /ipld/<obj2-cid>/a/aa/aaa/a/aa/aaa/a/aa/aaa point to?
# what does /ipld/<obj3-cid>/a/aa/aaa/a/aa/aaa/a/aa/aaa point to?
```

**Comment by jbenet** [comment]
I'm sure we can craft much worse things. but just a taste of what this enables. It's like a DAG `goto`

**Comment by dignifiedquire** [comment]
If we allow the traversal across object boundaries these paths are not unambiguous anymore. Look at this example:

``` yml

# AAA1
name: cool
value: 1
great: BBB/value

# AAA2
name: cooler
value: 2
great: BBB/value

# BBB
name: secret
value: ../value
```

In this case `great` is equal to `1` or `2` for `AAA1` and `AAA2` respectively. This to me seems very unintuitive and risky. Also what happens if the property does not exist, e.g.

``` yaml
# AAA3
name: something
great: BBB/value
```

then we look at

```
AAA3/great = ???
```
